#!/bin/bash
#bash for getting new addons, packaging them, creating addons.xml and md5 and update mirrorbrain
# create .zip files from addons git
/usr/local/bin/updaterepo
sleep 1
# create addons.xml for each repo
/usr/local/bin/repo_catxml-all
sleep 1 
# create addons.xml.md5 for each repo
/usr/local/bin/repo_catxml-md5

