#!/bin/bash

repos=("plugins" "skins" "scrapers" "scripts" "webinterfaces" "resources")
gitrepo="/home/git/addons-git"
dest="/var/www/downloads/addons"

#$gitrepo created with:
#rm -rf $gitrepo/* $dest/*
#for (( i=0; i<${#repos[*]}; i++ )); do
#  #git clone --no-checkout "git://xbmc.git.sourceforge.net/gitroot/xbmc/${repos[$i]}" "${gitrepo}/$repos{[$i]}"
#  git clone --no-checkout "git clone git://git.code.sf.net/p/xbmc/${repos[$i]}" "${gitrepo}/$repos"
#done

for (( i=0; i<${#repos[*]}; i++ )); do
  for j in `/usr/local/bin/gitbridge -i -r ${gitrepo}/${repos[$i]} -d ${dest} -i`; do
    for (( k=0; k<${#touchedbranches[*]}; k++ )); do
      if [ "${touchedbranches[$k]}" = "${j}" ]; then
        touchedbranches[k]=""
      fi
    done
    touchedbranches=( "${touchedbranches[@]}" "${j}" )
  done
done
